-- MySQL Script generated by MySQL Workbench
-- 06/07/16 21:10:21
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`proveedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`proveedor` ;

CREATE TABLE IF NOT EXISTS `mydb`.`proveedor` (
  `nom_proveedor` INT NOT NULL,
  `direccion_proveedor` VARCHAR(45) NOT NULL,
  `telefono_prov` VARCHAR(45) NOT NULL,
  `mail_prov` VARCHAR(45) NOT NULL,
  `direccion_prov` VARCHAR(45) NOT NULL,
  `rut_prov` VARCHAR(35) NOT NULL,
  `email_prov` VARCHAR(45) NULL,
  `reg_prov` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`nom_proveedor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`producto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`producto` ;

CREATE TABLE IF NOT EXISTS `mydb`.`producto` (
  `idproducto` INT NOT NULL,
  `detalle_producto` VARCHAR(45) NOT NULL,
  `nom_producto` VARCHAR(45) NOT NULL,
  `precio_prod` VARCHAR(45) NOT NULL,
  `tipo_producto` VARCHAR(45) NOT NULL,
  `imagen` VARCHAR(45) NULL,
  `proveedor_nom_proveedor` INT NOT NULL,
  PRIMARY KEY (`idproducto`, `proveedor_nom_proveedor`),
  INDEX `fk_producto_proveedor1_idx` (`proveedor_nom_proveedor` ASC),
  CONSTRAINT `fk_producto_proveedor1`
    FOREIGN KEY (`proveedor_nom_proveedor`)
    REFERENCES `mydb`.`proveedor` (`nom_proveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`cliente` ;

CREATE TABLE IF NOT EXISTS `mydb`.`cliente` (
  `rut_cliente` INT NOT NULL,
  `apellido_cliente` VARCHAR(45) NOT NULL,
  `nom_cliente` VARCHAR(45) NOT NULL,
  `mail_cliente` VARCHAR(45) NOT NULL,
  `direccion_cliente` VARCHAR(45) NOT NULL,
  `clave_cliente` VARCHAR(35) NOT NULL,
  `num_tarjeta` VARCHAR(45) NULL,
  `ciudad` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`rut_cliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`administrador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`administrador` ;

CREATE TABLE IF NOT EXISTS `mydb`.`administrador` (
  `id_admin` INT NOT NULL,
  `nom_admin` VARCHAR(45) NOT NULL,
  `cargo_admin` VARCHAR(45) NOT NULL,
  `clave_admin` VARCHAR(35) NOT NULL,
  PRIMARY KEY (`id_admin`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`stock`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`stock` ;

CREATE TABLE IF NOT EXISTS `mydb`.`stock` (
  `registro` VARCHAR(35) NOT NULL,
  `producto_idproducto` INT NOT NULL,
  PRIMARY KEY (`producto_idproducto`),
  CONSTRAINT `fk_stock_producto`
    FOREIGN KEY (`producto_idproducto`)
    REFERENCES `mydb`.`producto` (`idproducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ventas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ventas` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ventas` (
  `id_ventas` INT NOT NULL,
  `fecha_venta` VARCHAR(45) NOT NULL,
  `num_venta` VARCHAR(45) NOT NULL,
  `cod_venta` VARCHAR(35) NOT NULL,
  `cliente_rut_cliente` INT NOT NULL,
  PRIMARY KEY (`id_ventas`, `cliente_rut_cliente`),
  INDEX `fk_ventas_cliente1_idx` (`cliente_rut_cliente` ASC),
  CONSTRAINT `fk_ventas_cliente1`
    FOREIGN KEY (`cliente_rut_cliente`)
    REFERENCES `mydb`.`cliente` (`rut_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`producto_has_ventas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`producto_has_ventas` ;

CREATE TABLE IF NOT EXISTS `mydb`.`producto_has_ventas` (
  `producto_idproducto` INT NOT NULL,
  `ventas_id_ventas` INT NOT NULL,
  PRIMARY KEY (`producto_idproducto`, `ventas_id_ventas`),
  INDEX `fk_producto_has_ventas_ventas1_idx` (`ventas_id_ventas` ASC),
  INDEX `fk_producto_has_ventas_producto1_idx` (`producto_idproducto` ASC),
  CONSTRAINT `fk_producto_has_ventas_producto1`
    FOREIGN KEY (`producto_idproducto`)
    REFERENCES `mydb`.`producto` (`idproducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_producto_has_ventas_ventas1`
    FOREIGN KEY (`ventas_id_ventas`)
    REFERENCES `mydb`.`ventas` (`id_ventas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
